# Generated by Django 5.2.4 on 2025-07-27 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20250727_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
