# Generated by Django 5.2.4 on 2025-07-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_is_active_alter_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Dining'), ('wellness', 'Wellness & Spa'), ('transport', 'Transportation'), ('tours', 'Tours & Activities'), (
                'housekeeping', 'Housekeeping'), ('concierge', 'Concierge Services'), ('business', 'Business Services'), ('entertainment', 'Entertainment')], default='concierge', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='is_available_24_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='requires_advance_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='advance_booking_hours',
            field=models.PositiveIntegerField(
                default=24, help_text='Hours in advance required for booking'),
        ),
        migrations.AddField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(
                blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='max_capacity',
            field=models.PositiveIntegerField(
                blank=True, help_text='Maximum number of people', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(
                blank=True, help_text='Where the service is provided', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(
                blank=True, null=True, upload_to='service_images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='terms_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
